// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/tasksync.proto

package tasksyncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskSyncService_PutTask_FullMethodName    = "/tasksync.TaskSyncService/PutTask"
	TaskSyncService_GetTask_FullMethodName    = "/tasksync.TaskSyncService/GetTask"
	TaskSyncService_DeleteTask_FullMethodName = "/tasksync.TaskSyncService/DeleteTask"
)

// TaskSyncServiceClient is the client API for TaskSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskSync gRPC service.
type TaskSyncServiceClient interface {
	// Create or update a task.
	PutTask(ctx context.Context, in *PutTaskRequest, opts ...grpc.CallOption) (*PutTaskResponse, error)
	// Retrieve a task.
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	// Delete a task.
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
}

type taskSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskSyncServiceClient(cc grpc.ClientConnInterface) TaskSyncServiceClient {
	return &taskSyncServiceClient{cc}
}

func (c *taskSyncServiceClient) PutTask(ctx context.Context, in *PutTaskRequest, opts ...grpc.CallOption) (*PutTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutTaskResponse)
	err := c.cc.Invoke(ctx, TaskSyncService_PutTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskSyncServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, TaskSyncService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskSyncServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskResponse)
	err := c.cc.Invoke(ctx, TaskSyncService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskSyncServiceServer is the server API for TaskSyncService service.
// All implementations must embed UnimplementedTaskSyncServiceServer
// for forward compatibility.
//
// TaskSync gRPC service.
type TaskSyncServiceServer interface {
	// Create or update a task.
	PutTask(context.Context, *PutTaskRequest) (*PutTaskResponse, error)
	// Retrieve a task.
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	// Delete a task.
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
	mustEmbedUnimplementedTaskSyncServiceServer()
}

// UnimplementedTaskSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskSyncServiceServer struct{}

func (UnimplementedTaskSyncServiceServer) PutTask(context.Context, *PutTaskRequest) (*PutTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutTask not implemented")
}
func (UnimplementedTaskSyncServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskSyncServiceServer) DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedTaskSyncServiceServer) mustEmbedUnimplementedTaskSyncServiceServer() {}
func (UnimplementedTaskSyncServiceServer) testEmbeddedByValue()                         {}

// UnsafeTaskSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskSyncServiceServer will
// result in compilation errors.
type UnsafeTaskSyncServiceServer interface {
	mustEmbedUnimplementedTaskSyncServiceServer()
}

func RegisterTaskSyncServiceServer(s grpc.ServiceRegistrar, srv TaskSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskSyncService_ServiceDesc, srv)
}

func _TaskSyncService_PutTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskSyncServiceServer).PutTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskSyncService_PutTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskSyncServiceServer).PutTask(ctx, req.(*PutTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskSyncService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskSyncServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskSyncService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskSyncServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskSyncService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskSyncServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskSyncService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskSyncServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskSyncService_ServiceDesc is the grpc.ServiceDesc for TaskSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tasksync.TaskSyncService",
	HandlerType: (*TaskSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutTask",
			Handler:    _TaskSyncService_PutTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskSyncService_GetTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskSyncService_DeleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tasksync.proto",
}
